### ISSUE TITLE
Site não é gerado usando Node.js 18.17.1

### ISSUE THREAD

**Issue by flavioipiranga** [Franzininho/docs-franzininho-site#45]
Realizei o clone do repositório, entrei na pasta do repositório e segui os passos:

1. `yarn install`

2. `yarn start`

O resultado do último comando foi:
```
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/ubuntu/playground/docs-franzininho-site/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ubuntu/playground/docs-franzininho-site/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/ubuntu/playground/docs-franzininho-site/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/ubuntu/playground/docs-franzininho-site/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/ubuntu/playground/docs-franzininho-site/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/ubuntu/playground/docs-franzininho-site/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/ubuntu/playground/docs-franzininho-site/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/ubuntu/playground/docs-franzininho-site/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/ubuntu/playground/docs-franzininho-site/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/ubuntu/playground/docs-franzininho-site/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/ubuntu/playground/docs-franzininho-site/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.1
error Command failed with exit code 1.
```

Para resolver o error foi preciso utilizar: ` export NODE_OPTIONS=--openssl-legacy-provider`

Após realizar uma rápida pesquisa encontrei uma issue do docusaurus(https://github.com/leoafarias/fvm/pull/525/commits/8baf40260d3cc1458c99e6d35feb4842e795d3bf), ela recomenda utilizar uma versão mais atual. Ao utilizar a change dessa issue o site foi gerado com sucesso.

Entretanto isso me levou a verificar a versão mais atual do docusaurus e vi que ele está na 3.1.1. 

Gostaria de saber o que acham a respeito de realizar uma atualização para a versão 3.1.1.

**Comment by flavioipiranga** [comment]
Após realizar mais alguns testes foi possível notar que seguindo os passos abaixo o site é construído com sucesso:

1. Atualizar o arquivo `package.json` para usar o docusaurus 3.1.1 e o React 18.
2. Executar o comando `npx yarn-audit-fix`
3. Alterar os links utilizados para o novo modelo da versão 3 do docusaurus

**Comment by FBSeletronica** [comment]
Obrigado Flávio
